# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
    tags: ['v*']
  pull_request:
    branches: [ "master" ]
permissions:
  contents: write
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.1'

    - name: Install dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Build binary
      env:
        OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
        ENVIRONMENT: production
      run: |
        go build -v -ldflags "-X 'weathering-with-go/config.BuildTimeAPIKey=$OPENWEATHERMAP_API_KEY' -X 'weathering-with-go/config.Environment=$ENVIRONMENT'" -o weathering-with-go .
        chmod +x weathering-with-go

    - name: Test
      run: go test -v ./...

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: weathering-with-go-binary
        path: weathering-with-go
        retention-days: 7

  create-release:
    if: github.ref_type == 'tag'
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          artifacts/weathering-with-go-binary/weathering-with-go
        generate_release_notes: true
        draft: false
        prerelease: false