# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.1'

    - name: Install dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Build binary
      env:
        OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
      run: |
        echo "API Key length: ${#OPENWEATHERMAP_API_KEY}"
        echo "API Key content (with quotes): '$OPENWEATHERMAP_API_KEY'"
        if [ -n "$OPENWEATHERMAP_API_KEY" ]; then
          echo "API Key is set (first 4 chars: ${OPENWEATHERMAP_API_KEY:0:4}...)"
        else
          echo "API Key is NOT set or empty"
        fi
        echo "Building with ldflags..."
        go build -v -ldflags "-X 'weathering-with-go/config.BuildTimeAPIKey=$OPENWEATHERMAP_API_KEY'" -o weathering-with-go .
        chmod +x weathering-with-go

    - name: Test
      run: go test -v ./...

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: weathering-with-go-binary
        path: weathering-with-go
        retention-days: 7
